name: Generate Snake Game Animation

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Snake Animation generation
      - name: Generate Snake Animation
        uses: Platane/snk@2.0.0
        with:
          github_user_name: Zero-7-1
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the generated snake.svg to the output branch
      - name: Deploy Snake Animation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
